name:                generic-constructors
version:             0.1.0.0
github:              "akrmn/generic-constructors"
license:             BSD3
author:              "Moisés Ackerman"
maintainer:          "moises@akr.mn"
copyright:           "2020 Moisés Ackerman"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/akrmn/generic-constructors#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  generic-constructors-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-constructors
